require('exosyphon.lazy')
require('exosyphon.remaps')
require('exosyphon.options')
vim.cmd("colorscheme gruvbox")
vim.api.nvim_set_hl(0, "IlluminatedWordText", { link = "Visual" })
vim.api.nvim_set_hl(0, "IlluminatedWordRead", { link = "Visual" })
vim.api.nvim_set_hl(0, "IlluminatedWordWrite", { link = "Visual" })
