require('exosyphon.lazy')
require('exosyphon.remaps')
require('exosyphon.options')
vim.cmd("colorscheme gruvbox")
vim.cmd('hi IlluminatedWordText guibg=#5e4a3a gui=none')
vim.cmd('hi IlluminatedWordRead guibg=#5e4a3a gui=none')
vim.cmd('hi IlluminatedWordWrite guibg=#5e4a3a gui=none')
